# Generated by Django 3.0.6 on 2020-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name of Language programming')),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Name of Language programming',
                'verbose_name_plural': "Name's of Language programming",
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Name of sity', 'verbose_name_plural': "Name of sity's"},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of sity'),
        ),
    ]
